# Generated by Django 5.1.3 on 2024-11-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
